# Generated by Django 4.1.4 on 2022-12-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='customers',
        ),
    ]
