# Generated by Django 4.1.4 on 2022-12-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='meals',
            new_name='mealname',
        ),
        migrations.AlterField(
            model_name='meals',
            name='prices',
            field=models.FloatField(max_length=20),
        ),
    ]
